name: iOS CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using iPhone 16 (iOS 18.2) Simulator
    runs-on: macos-14  # Ensures Xcode 16.2 compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install iOS 18.2 Simulator (If Needed)
        run: sudo xcodebuild -downloadPlatform iOS || echo "Skipping, already installed"

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Set Default Scheme
        run: |
          echo "Detecting default scheme..."
          scheme_list=$(xcodebuild -list -json)
          default=$(echo "$scheme_list" | jq -r '.project.schemes[0]')
          echo "Using default scheme: $default"
          echo $default > default_scheme.txt

      - name: Select iPhone 16 (iOS 18.2) Simulator
        run: |
          echo "Selecting iPhone 16 with iOS 18.2..."
          device_id="6931CB3E-634D-434E-8C1F-2F768C466160"

          if [ -z "$device_id" ]; then
            echo "❌ No compatible iOS 18.2 simulator found! Aborting."
            exit 1
          fi
          
          echo "✅ Selected Simulator: iPhone 16 ($device_id)"
          echo $device_id > selected_simulator.txt
          
          # Ensure the simulator is booted
          xcrun simctl boot "$device_id" || echo "Skipping boot if already running"

      - name: Build
        env:
          platform: "iOS Simulator"
        run: |
          device=$(cat selected_simulator.txt)
          scheme=$(cat default_scheme.txt)
          file_to_build=$(ls -A | grep -iE '\.xcworkspace$|\.xcodeproj$' | head -1)

          echo "Building for simulator: $device"
          xcodebuild build-for-testing -scheme "$scheme" -project "$file_to_build" -destination "platform=$platform,id=$device,OS=18.2" | xcpretty

      - name: Test
        env:
          platform: "iOS Simulator"
        run: |
          device=$(cat selected_simulator.txt)
          scheme=$(cat default_scheme.txt)
          file_to_build=$(ls -A | grep -iE '\.xcworkspace$|\.xcodeproj$' | head -1)

          echo "Running tests on: $device"
          xcodebuild test-without-building -scheme "$scheme" -project "$file_to_build" -destination "platform=$platform,id=$device,OS=18.2" | xcpretty