name: iOS CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using iOS 18.0 Simulator
    runs-on: macos-14  # Ensure compatibility with Xcode 16.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install iOS 18.0 Simulator (If Needed)
        run: sudo xcodebuild -downloadPlatform iOS || echo "Skipping, already installed"

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Set Default Scheme
        run: |
          echo "Detecting default scheme..."
          scheme_list=$(xcodebuild -list -json)
          default=$(echo "$scheme_list" | jq -r '.project.schemes[0]')
          echo "Using default scheme: $default"
          echo $default > default_scheme.txt

      - name: Build
        env:
          platform: "iOS Simulator"
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*? \([0-9\.]+\)' | grep "18.0" | head -1 | awk -F '[()]' '{print $1}')
          scheme=$(cat default_scheme.txt)
          echo "Selected Simulator: $device"
          if [ -z "$device" ]; then echo "❌ No compatible simulator found!" && exit 1; fi
          file_to_build=$(ls -A | grep -iE '\.xcworkspace$|\.xcodeproj$' | head -1)
          xcodebuild build-for-testing -scheme "$scheme" -project "$file_to_build" -destination "platform=$platform,name=$device,OS=18.0" | xcpretty

      - name: Test
        env:
          platform: "iOS Simulator"
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*? \([0-9\.]+\)' | grep "18.0" | head -1 | awk -F '[()]' '{print $1}')
          scheme=$(cat default_scheme.txt)
          echo "Running tests on: $device"
          if [ -z "$device" ]; then echo "❌ No compatible simulator found!" && exit 1; fi
          file_to_build=$(ls -A | grep -iE '\.xcworkspace$|\.xcodeproj$' | head -1)
          xcodebuild test-without-building -scheme "$scheme" -project "$file_to_build" -destination "platform=$platform,name=$device,OS=18.0" | xcpretty